Repository LiamANeeson/MSc-Game-Engine-Project-Website, pull requests merged in 2022-12, with the labels that each got.

#95 Tutorial fix
  client/package-lock.json
  client/package.json
  client/src/Assets/Images/dwnldHGE/Download_GE.png
  client/src/Components/CodeBox/CodeBox.css
  client/src/Components/CodeBox/CodeBox.jsx
  client/src/Components/Sidebar/Sidebar.js
  client/src/Components/Sidebar/SidebarData.js
  client/src/Components/TreeMap/TreeMap.js
  client/src/Pages/Tutorial/Tutorial.css
  client/src/Pages/Tutorial/Tutorial.js
  client/src/Pages/Tutorial/Tutorial_Subsections/AddObjects.js
  client/src/Pages/Tutorial/Tutorial_Subsections/CreateProject.js
  client/src/Pages/Tutorial/Tutorial_Subsections/CreateScene.js
  client/src/Pages/Tutorial/Tutorial_Subsections/GettingStarted.js
  client/src/Pages/Tutorial/Tutorial_Subsections/Physics.js
  client/src/Pages/Tutorial/Tutorial_Subsections/Scripting.js
  client/src/Pages/Tutorial/Tutorial_Subsections/tut_subsections.css
  package-lock.json
  package.json
Labels: bug, enhancement

#98 Fixed Docs button, added some content.
  client/src/App.js
  client/src/Pages/Docs/Documentation.css
  client/src/Pages/Docs/Documentation.js
Labels: bug, enhancement

#97 Dashboard admin
  client/package-lock.json
  client/src/Pages/Community/Question.js
  client/src/Pages/Community/QuestionDetail.js
  client/src/Pages/Login/Login.js
  client/src/Pages/Login/ResetPassword.js
  client/src/features/APIs/api.js
  client/src/validation/userValidation.js
  controllers/answerController.js
  controllers/questionController.js
  controllers/userController.js
  package-lock.json
  routes/answerRoute.js
  routes/questionRoutes.js
Labels: enhancement

#118 validation fix
  client/src/validation/postValidation.js
  client/src/validation/profileValidation.js
  client/src/validation/userValidation.js
Labels: bug

#140 Wrapping limit on followed and user posts
  client/src/Pages/Community/Community.css
  client/src/Pages/Community/Question.js
  client/src/Pages/Community/Search/style.module.css
  client/src/Pages/Login/Login.js
  client/src/Pages/Profile/Profile.css
  client/src/Pages/Profile/Profile.js
  client/src/features/APIs/api.js
  client/src/features/auth/authService.js
  client/src/validation/userValidation.js
  controllers/profileController.js
  controllers/questionController.js
  controllers/userController.js
  models/questionModel.js
  models/userModel.js
  routes/questionRoutes.js
Labels: enhancement

#134 Login required fix
  client/src/Pages/Profile/Profile.js
  client/src/Pages/UploadFile/UploadFile.js
  controllers/questionController.js
Labels: bug

#145 Profile information will be synchronized to the community page
  client/src/Pages/Community/Question.css
  client/src/Pages/Community/Question.js
  client/src/Pages/Community/QuestionDetail.css
  client/src/Pages/Community/QuestionDetail.js
  client/src/Pages/Profile/Profile.js
  controllers/answerController.js
  controllers/profileController.js
  models/answerModel.js
  models/questionModel.js
Labels: bug

#150 Fix home page content
  client/src/Pages/Home/Home.js
Labels: enhancement

#149 Gamify tutorials
  client/src/Pages/Tutorial/Tutorial_Subsections/AddObjects.js
  client/src/Pages/Tutorial/Tutorial_Subsections/CreateProject.js
  client/src/Pages/Tutorial/Tutorial_Subsections/CreateScene.js
  client/src/Pages/Tutorial/Tutorial_Subsections/EntitiesComponents.js
  client/src/Pages/Tutorial/Tutorial_Subsections/GettingStarted.js
  client/src/Pages/Tutorial/Tutorial_Subsections/Physics.js
  client/src/Pages/Tutorial/Tutorial_Subsections/Scripting.js
  client/src/Pages/Tutorial/Tutorial_Subsections/tut_subsections.css
  client/src/Pages/Tutorial/tutorial_game_subsections/GameCreateProject.js
  client/src/Pages/Tutorial/tutorial_game_subsections/GameCreateScene.js
  client/src/Pages/Tutorial/tutorial_game_subsections/GameTutSubSec.css
Labels: bug, enhancement

#153 question detail page ui
  client/src/Pages/Community/Question.css
  client/src/Pages/Community/QuestionDetail.css
  client/src/Pages/Community/QuestionDetail.js
  routes/questionRoutes.js
Labels: bug

#159 Game tutorial branch
  client/src/App.js
  client/src/Assets/Images/dwnldHGE/Download_GE.png
  client/src/Assets/Images/gameTutImages/AddingSprites.png
  client/src/Assets/TileMap/Tilemap.zip
  client/src/Components/GameTutSidebar/GameSidebarData.js
  client/src/Pages/Home/Home.js
  client/src/Pages/Tutorial/Tutorial.js
  client/src/Pages/Tutorial/Tutorial_Subsections/Scripting.js
  client/src/Pages/Tutorial/tutorial_game_subsections/AddingScripts.js
  client/src/Pages/Tutorial/tutorial_game_subsections/AddingSprites.js
  client/src/Pages/Tutorial/tutorial_game_subsections/GameGettingStarted.js
  client/src/Pages/Tutorial/tutorial_game_subsections/GameTutSubSec.css
  client/src/Pages/Tutorial/tutorial_game_subsections/MakeAGame.js
  client/src/Pages/Tutorial/tutorial_game_subsections/PlayingTheGame.js
  client/src/Pages/Tutorial/tutorial_game_subsections/Prerequisites.js
Labels: enhancement

#161 fix reset password by email
  client/src/App.js
  client/src/Pages/Login/ResetPassword.js
  client/src/features/auth/authService.js
  client/src/features/auth/authSlice.js
  client/src/validation/userValidation.js
  controllers/userController.js
  routes/userRoutes.js
Labels: bug
